### ISSUE TITLE
report SyntaxError

### ISSUE THREAD

**Issue by hantmac** [dannysofftie/mysql-mongo-migrate#1]
os: centos 7
```
[root@localhost mysql-mongo-migrate]# mysql-mongo-migrate
/usr/lib/node_modules/mysql-mongo-migrate/index.js:55
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

**Comment by dan-kimani** [comment]
Which Node.js version are you using?

**Comment by hantmac** [comment]
> ode.js version are you using?

v6.16.0

Is it too low?

**Comment by dan-kimani** [comment]
Update Node.js to a recent version, preferably Node v8 or higher. The package is written in TypeScript and targets es2018, async and await is not supported by Node v6

**Comment by hantmac** [comment]
I update node version, and it worked!
BUT, How can I Specify the port number of mysql? My port is not 3306, but your tool use it default.

**Comment by dan-kimani** [comment]
Uses 3306 as the default port, will push that in the next release

**Comment by hantmac** [comment]
OK, Thank u anyway.
